// Generates app + tray icons without any image dependencies.
// Pure-JS PNG encoder + a tiny SDF rasterizer (rounded square + check mark).
//
// Outputs:
//   build/icon.png            512x512  (electron-builder converts to .ico)
//   electron/trayIconData.ts  base64 32x32 PNG embedded as a TS module,
//                             so the tray icon needs no asset copying in dev or prod.
import { deflateSync } from 'node:zlib'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

// ---------- minimal PNG encoder (RGBA, no filtering) ----------
const CRC_TABLE = new Int32Array(256).map((_, n) => {
  let c = n
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
  return c
})
function crc32(buf) {
  let c = 0xffffffff
  for (const b of buf) c = CRC_TABLE[(c ^ b) & 0xff] ^ (c >>> 8)
  return (c ^ 0xffffffff) >>> 0
}
function chunk(type, data) {
  const len = Buffer.alloc(4)
  len.writeUInt32BE(data.length)
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data])
  const crc = Buffer.alloc(4)
  crc.writeUInt32BE(crc32(body))
  return Buffer.concat([len, body, crc])
}
function encodePng(width, height, rgba) {
  const sig = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])
  const ihdr = Buffer.alloc(13)
  ihdr.writeUInt32BE(width, 0)
  ihdr.writeUInt32BE(height, 4)
  ihdr[8] = 8 // bit depth
  ihdr[9] = 6 // color type RGBA
  // raw scanlines, each prefixed with filter byte 0
  const raw = Buffer.alloc((width * 4 + 1) * height)
  for (let y = 0; y < height; y++) {
    raw[y * (width * 4 + 1)] = 0
    rgba.copy(raw, y * (width * 4 + 1) + 1, y * width * 4, (y + 1) * width * 4)
  }
  return Buffer.concat([
    sig,
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0))
  ])
}

// ---------- SDF shapes ----------
function sdRoundedRect(px, py, cx, cy, hw, hh, r) {
  const qx = Math.abs(px - cx) - (hw - r)
  const qy = Math.abs(py - cy) - (hh - r)
  const ox = Math.max(qx, 0)
  const oy = Math.max(qy, 0)
  return Math.hypot(ox, oy) + Math.min(Math.max(qx, qy), 0) - r
}
function sdSegment(px, py, ax, ay, bx, by) {
  const pax = px - ax, pay = py - ay
  const bax = bx - ax, bay = by - ay
  const h = Math.max(0, Math.min(1, (pax * bax + pay * bay) / (bax * bax + bay * bay)))
  return Math.hypot(pax - bax * h, pay - bay * h)
}
const smooth = (d, aa) => Math.max(0, Math.min(1, 0.5 - d / aa))
const hex = (h) => [parseInt(h.slice(1, 3), 16), parseInt(h.slice(3, 5), 16), parseInt(h.slice(5, 7), 16)]

// Palette: deep navy tile, amber check
const BG = hex('#101A2D')
const EDGE = hex('#2A3B5C')
const AMBER = hex('#F2A93B')

function renderIcon(size, { pad = 0.04, tile = true } = {}) {
  const rgba = Buffer.alloc(size * size * 4)
  const aa = Math.max(1.25, size / 96) // anti-alias width in px
  const S = size
  const c = S / 2
  const half = S * (0.5 - pad)
  const radius = half * 0.42
  // check mark geometry (in unit space of the tile)
  const k = half * 2
  const x1 = c - k * 0.235, y1 = c + k * 0.02
  const x2 = c - k * 0.055, y2 = c + k * 0.20
  const x3 = c + k * 0.26, y3 = c - k * 0.185
  const stroke = k * 0.093

  for (let y = 0; y < S; y++) {
    for (let x = 0; x < S; x++) {
      const px = x + 0.5, py = y + 0.5
      let r = 0, g = 0, b = 0, a = 0

      if (tile) {
        const dTile = sdRoundedRect(px, py, c, c, half, half, radius)
        const tileA = smooth(dTile, aa)
        if (tileA > 0) {
          // subtle vertical shade + inner edge highlight
          const t = (py - (c - half)) / (2 * half)
          const shade = 1 - 0.16 * t
          r = BG[0] * shade; g = BG[1] * shade; b = BG[2] * shade
          const edge = smooth(Math.abs(dTile + aa * 1.6) - aa * 0.9, aa) * 0.5
          r += (EDGE[0] - r) * edge; g += (EDGE[1] - g) * edge; b += (EDGE[2] - b) * edge
          a = tileA
        }
      }

      const dCheck = Math.min(
        sdSegment(px, py, x1, y1, x2, y2),
        sdSegment(px, py, x2, y2, x3, y3)
      ) - stroke
      const chA = smooth(dCheck, aa)
      if (chA > 0) {
        r += (AMBER[0] - r) * chA
        g += (AMBER[1] - g) * chA
        b += (AMBER[2] - b) * chA
        a = Math.max(a, chA)
      }

      const i = (y * S + x) * 4
      rgba[i] = Math.round(r)
      rgba[i + 1] = Math.round(g)
      rgba[i + 2] = Math.round(b)
      rgba[i + 3] = Math.round(a * 255)
    }
  }
  return encodePng(S, S, rgba)
}

mkdirSync(join(root, 'build'), { recursive: true })
writeFileSync(join(root, 'build', 'icon.png'), renderIcon(512))
writeFileSync(join(root, 'build', 'icon-256.png'), renderIcon(256))

const tray32 = renderIcon(32, { pad: 0.0 })
const trayTs = `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// 32x32 PNG, embedded so the tray icon needs no asset pipeline.
export const TRAY_ICON_BASE64 =
  '${tray32.toString('base64')}'
`
writeFileSync(join(root, 'electron', 'trayIconData.ts'), trayTs)
console.log('icons written: build/icon.png (512), build/icon-256.png, electron/trayIconData.ts')
